package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CompetenceRequiseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceRequiseAllPropertiesEquals(CompetenceRequise expected, CompetenceRequise actual) {
        assertCompetenceRequiseAutoGeneratedPropertiesEquals(expected, actual);
        assertCompetenceRequiseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceRequiseAllUpdatablePropertiesEquals(CompetenceRequise expected, CompetenceRequise actual) {
        assertCompetenceRequiseUpdatableFieldsEquals(expected, actual);
        assertCompetenceRequiseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceRequiseAutoGeneratedPropertiesEquals(CompetenceRequise expected, CompetenceRequise actual) {
        assertThat(actual)
            .as("Verify CompetenceRequise auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceRequiseUpdatableFieldsEquals(CompetenceRequise expected, CompetenceRequise actual) {
        assertThat(actual)
            .as("Verify CompetenceRequise relevant properties")
            .satisfies(a -> assertThat(a.getObligatoire()).as("check obligatoire").isEqualTo(expected.getObligatoire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceRequiseUpdatableRelationshipsEquals(CompetenceRequise expected, CompetenceRequise actual) {
        assertThat(actual)
            .as("Verify CompetenceRequise relationships")
            .satisfies(a -> assertThat(a.getCompetence()).as("check competence").isEqualTo(expected.getCompetence()))
            .satisfies(a -> assertThat(a.getPoste()).as("check poste").isEqualTo(expected.getPoste()));
    }
}
