package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CompetenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceAllPropertiesEquals(Competence expected, Competence actual) {
        assertCompetenceAutoGeneratedPropertiesEquals(expected, actual);
        assertCompetenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceAllUpdatablePropertiesEquals(Competence expected, Competence actual) {
        assertCompetenceUpdatableFieldsEquals(expected, actual);
        assertCompetenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceAutoGeneratedPropertiesEquals(Competence expected, Competence actual) {
        assertThat(actual)
            .as("Verify Competence auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceUpdatableFieldsEquals(Competence expected, Competence actual) {
        assertThat(actual)
            .as("Verify Competence relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompetenceUpdatableRelationshipsEquals(Competence expected, Competence actual) {
        assertThat(actual)
            .as("Verify Competence relationships")
            .satisfies(a -> assertThat(a.getExpertses()).as("check expertses").isEqualTo(expected.getExpertses()));
    }
}
