package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmployeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeAllPropertiesEquals(Employe expected, Employe actual) {
        assertEmployeAutoGeneratedPropertiesEquals(expected, actual);
        assertEmployeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeAllUpdatablePropertiesEquals(Employe expected, Employe actual) {
        assertEmployeUpdatableFieldsEquals(expected, actual);
        assertEmployeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeAutoGeneratedPropertiesEquals(Employe expected, Employe actual) {
        assertThat(actual)
            .as("Verify Employe auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeUpdatableFieldsEquals(Employe expected, Employe actual) {
        assertThat(actual)
            .as("Verify Employe relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDateRecrutement()).as("check dateRecrutement").isEqualTo(expected.getDateRecrutement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmployeUpdatableRelationshipsEquals(Employe expected, Employe actual) {
        assertThat(actual)
            .as("Verify Employe relationships")
            .satisfies(a -> assertThat(a.getPoste()).as("check poste").isEqualTo(expected.getPoste()));
    }
}
