package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EpreuveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEpreuveAllPropertiesEquals(Epreuve expected, Epreuve actual) {
        assertEpreuveAutoGeneratedPropertiesEquals(expected, actual);
        assertEpreuveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEpreuveAllUpdatablePropertiesEquals(Epreuve expected, Epreuve actual) {
        assertEpreuveUpdatableFieldsEquals(expected, actual);
        assertEpreuveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEpreuveAutoGeneratedPropertiesEquals(Epreuve expected, Epreuve actual) {
        assertThat(actual)
            .as("Verify Epreuve auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEpreuveUpdatableFieldsEquals(Epreuve expected, Epreuve actual) {
        assertThat(actual)
            .as("Verify Epreuve relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getEnonce()).as("check enonce").isEqualTo(expected.getEnonce()))
            .satisfies(a -> assertThat(a.getDifficulte()).as("check difficulte").isEqualTo(expected.getDifficulte()))
            .satisfies(a -> assertThat(a.getDuree()).as("check duree").isEqualTo(expected.getDuree()))
            .satisfies(a -> assertThat(a.getNbQuestions()).as("check nbQuestions").isEqualTo(expected.getNbQuestions()))
            .satisfies(a -> assertThat(a.getGenereParIA()).as("check genereParIA").isEqualTo(expected.getGenereParIA()))
            .satisfies(a -> assertThat(a.getPublie()).as("check publie").isEqualTo(expected.getPublie()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEpreuveUpdatableRelationshipsEquals(Epreuve expected, Epreuve actual) {
        assertThat(actual)
            .as("Verify Epreuve relationships")
            .satisfies(a -> assertThat(a.getCompetence()).as("check competence").isEqualTo(expected.getCompetence()));
    }
}
