package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExpertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpertAllPropertiesEquals(Expert expected, Expert actual) {
        assertExpertAutoGeneratedPropertiesEquals(expected, actual);
        assertExpertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpertAllUpdatablePropertiesEquals(Expert expected, Expert actual) {
        assertExpertUpdatableFieldsEquals(expected, actual);
        assertExpertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpertAutoGeneratedPropertiesEquals(Expert expected, Expert actual) {
        assertThat(actual)
            .as("Verify Expert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpertUpdatableFieldsEquals(Expert expected, Expert actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpertUpdatableRelationshipsEquals(Expert expected, Expert actual) {
        assertThat(actual)
            .as("Verify Expert relationships")
            .satisfies(a -> assertThat(a.getCompetenceses()).as("check competenceses").isEqualTo(expected.getCompetenceses()));
    }
}
