package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuestionAskAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionAskAllPropertiesEquals(QuestionAsk expected, QuestionAsk actual) {
        assertQuestionAskAutoGeneratedPropertiesEquals(expected, actual);
        assertQuestionAskAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionAskAllUpdatablePropertiesEquals(QuestionAsk expected, QuestionAsk actual) {
        assertQuestionAskUpdatableFieldsEquals(expected, actual);
        assertQuestionAskUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionAskAutoGeneratedPropertiesEquals(QuestionAsk expected, QuestionAsk actual) {
        assertThat(actual)
            .as("Verify QuestionAsk auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionAskUpdatableFieldsEquals(QuestionAsk expected, QuestionAsk actual) {
        assertThat(actual)
            .as("Verify QuestionAsk relevant properties")
            .satisfies(a -> assertThat(a.getOrdre()).as("check ordre").isEqualTo(expected.getOrdre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuestionAskUpdatableRelationshipsEquals(QuestionAsk expected, QuestionAsk actual) {
        assertThat(actual)
            .as("Verify QuestionAsk relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
