package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReponseCandidatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseCandidatAllPropertiesEquals(ReponseCandidat expected, ReponseCandidat actual) {
        assertReponseCandidatAutoGeneratedPropertiesEquals(expected, actual);
        assertReponseCandidatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseCandidatAllUpdatablePropertiesEquals(ReponseCandidat expected, ReponseCandidat actual) {
        assertReponseCandidatUpdatableFieldsEquals(expected, actual);
        assertReponseCandidatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseCandidatAutoGeneratedPropertiesEquals(ReponseCandidat expected, ReponseCandidat actual) {
        assertThat(actual)
            .as("Verify ReponseCandidat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseCandidatUpdatableFieldsEquals(ReponseCandidat expected, ReponseCandidat actual) {
        assertThat(actual)
            .as("Verify ReponseCandidat relevant properties")
            .satisfies(a -> assertThat(a.getEstCorrecte()).as("check estCorrecte").isEqualTo(expected.getEstCorrecte()))
            .satisfies(a -> assertThat(a.getDateReponse()).as("check dateReponse").isEqualTo(expected.getDateReponse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseCandidatUpdatableRelationshipsEquals(ReponseCandidat expected, ReponseCandidat actual) {
        assertThat(actual)
            .as("Verify ReponseCandidat relationships")
            .satisfies(a -> assertThat(a.getQuestionAsk()).as("check questionAsk").isEqualTo(expected.getQuestionAsk()))
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
