package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResultatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatAllPropertiesEquals(Resultat expected, Resultat actual) {
        assertResultatAutoGeneratedPropertiesEquals(expected, actual);
        assertResultatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatAllUpdatablePropertiesEquals(Resultat expected, Resultat actual) {
        assertResultatUpdatableFieldsEquals(expected, actual);
        assertResultatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatAutoGeneratedPropertiesEquals(Resultat expected, Resultat actual) {
        assertThat(actual)
            .as("Verify Resultat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatUpdatableFieldsEquals(Resultat expected, Resultat actual) {
        assertThat(actual)
            .as("Verify Resultat relevant properties")
            .satisfies(a -> assertThat(a.getScoreTotal()).as("check scoreTotal").isEqualTo(expected.getScoreTotal()))
            .satisfies(a -> assertThat(a.getScoreMax()).as("check scoreMax").isEqualTo(expected.getScoreMax()))
            .satisfies(a -> assertThat(a.getPourcentage()).as("check pourcentage").isEqualTo(expected.getPourcentage()))
            .satisfies(a -> assertThat(a.getMention()).as("check mention").isEqualTo(expected.getMention()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatUpdatableRelationshipsEquals(Resultat expected, Resultat actual) {
        // empty method
    }
}
