package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RHAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRHAllPropertiesEquals(RH expected, RH actual) {
        assertRHAutoGeneratedPropertiesEquals(expected, actual);
        assertRHAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRHAllUpdatablePropertiesEquals(RH expected, RH actual) {
        assertRHUpdatableFieldsEquals(expected, actual);
        assertRHUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRHAutoGeneratedPropertiesEquals(RH expected, RH actual) {
        assertThat(actual)
            .as("Verify RH auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRHUpdatableFieldsEquals(RH expected, RH actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRHUpdatableRelationshipsEquals(RH expected, RH actual) {
        // empty method
    }
}
