package com.devdouanla.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SessionTestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTestAllPropertiesEquals(SessionTest expected, SessionTest actual) {
        assertSessionTestAutoGeneratedPropertiesEquals(expected, actual);
        assertSessionTestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTestAllUpdatablePropertiesEquals(SessionTest expected, SessionTest actual) {
        assertSessionTestUpdatableFieldsEquals(expected, actual);
        assertSessionTestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTestAutoGeneratedPropertiesEquals(SessionTest expected, SessionTest actual) {
        assertThat(actual)
            .as("Verify SessionTest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTestUpdatableFieldsEquals(SessionTest expected, SessionTest actual) {
        assertThat(actual)
            .as("Verify SessionTest relevant properties")
            .satisfies(a -> assertThat(a.getScoreObtenu()).as("check scoreObtenu").isEqualTo(expected.getScoreObtenu()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTestUpdatableRelationshipsEquals(SessionTest expected, SessionTest actual) {
        assertThat(actual)
            .as("Verify SessionTest relationships")
            .satisfies(a -> assertThat(a.getResultat()).as("check resultat").isEqualTo(expected.getResultat()))
            .satisfies(a -> assertThat(a.getEvaluation()).as("check evaluation").isEqualTo(expected.getEvaluation()))
            .satisfies(a -> assertThat(a.getEpreuves()).as("check epreuves").isEqualTo(expected.getEpreuves()));
    }
}
