# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: postgres
    password: 1234

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2VlZWQ2ODEyYzk3MDI0ZjMxMTJiNTY2MGZjZGNkM2Y0NTZiYzEzNzZmNDE1Mjk0MTc3NzVhMTBmYWQ4YzM1NGQ0ZWMyM2Q3Y2U2MWM4ZGJiZjhkZjRkZmNlZDRjMjNmZDc2MjU1Zjk1Y2EzYTI5OTg3YzNjNDNiMGFhMTE5YmQ=
